version: "3.9"
services:
  db:
    image: mysql:8.4.3
    container_name: hhplus_mysql_container
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./database/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7.2.1
    container_name: hhplus_redis_container
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.cnf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app_network

volumes:
  db_data:
  redis_data:

networks:
  app_network:
